### Creates a User

POST http://localhost:3000/user/
Content-Type: application/json

{
    "name": "Morgan",
    //TODO: Stop blank emails from submitting
    "email": "",
    "password": "password123"
}


### Gets a User by ID
//"fd511dec-4660-4029-bcd1-7b3207a62b16"
GET http://localhost:3000/user/fd511dec-4660-4029-bcd1-7b3207a62b16


### Gets a User by Email
// "morgan@test.com"
GET http://localhost:3000/user?email=morgan@test.com


### Updates a User's name

PATCH http://localhost:3000/user/fd511dec-4660-4029-bcd1-7b3207a62b16
Content-Type: application/json

{
    
    "password": "password123"
}


### Deletes User

DELETE  http://localhost:3000/user/f0b9ece3-f346-4bf3-8c8c-1ad407abcbb4
