### Signs up user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}



### Signs in user

POST http://localhost:3000/auth/signin HTTP/1.1
Content-Type: application/json


{
  "username": "test@test.com",
  "password": "password123"
}
